### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by fclairamb** [andrewarrow/paradise_ftp#10]
Hi, 

Thank you very much for your work. I couldn't find any other go library that would at least work on modern systems.

I made a fork ( https://github.com/fclairamb/ftpserver ) and I just realised you didn't put a licence on it.

Could you add one ? I don't have any particular preference.

**Comment by andrewarrow** [comment]
sure, i checked in MIT license to master just now. thanks!

**Comment by fclairamb** [comment]
@andrewarrow : Thank you !
